name: Notification Discord après génération d'article

on:
  push:
    branches:
      - main

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo github
        uses: actions/checkout@v4

      - name: Reprendre les informations de l'article
        run: |
          ARTICLE_FILE=$(ls -t blog/*.md | head -1)
          ARTICLE_TITLE=$(grep "^title:" "$ARTICLE_FILE" | sed 's/^title: "//' | sed 's/"$//')
          ARTICLE_SUMMARY=$(grep "^summary:" "$ARTICLE_FILE" | sed 's/^summary: "//' | sed 's/"$//')
          echo "ARTICLE_TITLE=$ARTICLE_TITLE" >> $GITHUB_ENV
          echo "ARTICLE_SUMMARY=$ARTICLE_SUMMARY" >> $GITHUB_ENV

      - name: Envoyer une notification sur Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          PAYLOAD=$(jq -n \
            --arg title "$ARTICLE_TITLE" \
            --arg summary "$ARTICLE_SUMMARY" \
            '{ "content": "**Nouvel Article généré par IA !**\n\n**Titre de l'\''article :** \($title)\n\n**Résumé :** \($summary)" }'
          )
          
          curl -sS -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"