name: Générer un article IA 
on:
  pull_request:
    branches: 
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs: 
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dépendances
        run: npm install

      - name: Générer l'article avec la clé d'OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/generate-article.js

      - name: Commit et push de l'articlé généré
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add blog/
          git commit -m "Mise à jour de l'article généré"
          git push origin HEAD:${{ github.head_ref }}

      - name : Sauvegarder l'arcticle en artefact
        uses: actions/upload-artifact@v4
        with:
          name: article généré
          path: blog/